### ISSUE TITLE
Hood.ie server crashing after a day or two, also crashes my browser-tab

### ISSUE THREAD

**Issue by TrySpace** [hoodiehq/hoodie-server#261]
So after a day or so, the node-server won't reply, or probably it does, and crashes the browser-tab of the app-page

When I terminate hoodie in the console, this happens:

`Stopping CouchDB...`

`Stopping CouchDB...
Error: spawn EMFILE
    at errnoException (child_process.js:980:11)
    at ChildProcess.spawn (child_process.js:927:11)
    at exports.spawn (child_process.js:715:9)
    at MultiCouch.stop (/var/www/myapp/node_modules/hoodie-server/node_modules/multicouch/lib/multicouch.js:118:19)
    at Object.exports.stop (/var/www/myapp/node_modules/hoodie-server/lib/couchdb/index.js:181:11)
    at process.<anonymous> (/var/www/myapp/node_modules/hoodie-server/lib/couchdb/index.js:76:13)
    at process.EventEmitter.emit (events.js:95:17)
    at process.exit (node.js:707:17)
    at MultiCouch.<anonymous> (/var/www/myapp/node_modules/hoodie-server/lib/couchdb/index.js:85:15)
    at MultiCouch.g (events.js:175:14)`

After restarting hoodie everything works fine again..

I am using the dynamic '<script src="/_api/_files/hoodie.js"></script>' not sure if it matters. I'm also not clear how the dynamic script differs.

**Comment by boennemann** [comment]
The code that was probably causing this is pretty much 100% gone with the hoodie-server rewrite. I'm closing this for now, and we can reopen as soon as we're having the same problem again.
