### ISSUE TITLE
stopping hoodie doesn't stop couchDB

### ISSUE THREAD

**Issue by ronyrun** [hoodiehq/hoodie-server#342]
Stopping CouchDB...

Stopping CouchDB...
node.js:627
        throw errnoException(err, 'kill');
              ^
Error: kill ESRCH
    at exports._errnoException (util.js:746:11)
    at process.kill (node.js:627:15)
    at MultiCouch.stop (C:\Users\Rony\Dev\ron\node_modules\hoodie-server\node_modules\multicouch\lib\multicouch.js:114:15)
    at Object.exports.stop (C:\Users\Rony\Dev\ron\node_modules\hoodie-server\lib\couchdb\index.js:181:11)
    at process.<anonymous> (C:\Users\Rony\Dev\ron\node_modules\hoodie-server\lib\couchdb\index.js:84:13)
    at process.emit (events.js:104:17)
    at Signal.wrap.onsignal (node.js:655:46)

**Comment by boennemann** [comment]
We switched PouchDB e0184a67ce5a1d176f0955785c6b84cfe2aff32d
