### ISSUE TITLE
TypeError: Invalid Version: 72869b8

### ISSUE THREAD

**Issue by millisami** [hoodiehq/hoodie-server#512]
Been trying to create a simple hoodie app and connect with the CouchDB, its been 2 days and finally the database connects, but comes up another error after errors... 
And BTW I'm using Clouant's db.

Reading config from /Users/millisami/Hoodieaps/flourish/data/config.json.

```
hoodie start --verbose                                                                                                                                                    

.d$b.  .d$b.  .d$$$$$$b.    .d$$$$$$b.  .d$$$$$$b.  .d$b..d$$$$$$$$b.
$$$$$..$$$$$.$$$$$$$$$$$b .$$$$$$$$$$$b $$$$$$$$$$b $$$$$$$$$$$$$$$P'
$$$$$$$$$$$$d$$$$$$$$$$$$bd$$$$$$$$$$$$b$$$$$$$$$$$b$$$$$$$$$$$$$$$b.
$$$$$$$$$$$$Q$$$$$$$$$$$$PQ$$$$$$$$$$$$P$$$$$$$$$$$P$$$$$$$$$$$$$$$P'
$$$$$´`$$$$$'$$$$$$$$$$$$''$$$$$$$$$$$$'$$$$$$$$$$P $$$$$$$$$$$$$$$b.
'Q$P'  'Q$P'  'Q$$$$$$P'    'Q$$$$$$P'  'Q$$$$$$$P  'Q$P''Q$$$$$$$$P'

Version: 0.6.3 (node v2.3.0, npm 2.15.11, platform: darwin)

sys is deprecated. Use util instead.
Initializing...
Reading config from /Users/millisami/Hoodieaps/funcky/data/config.json.
Using remote CouchDB: https://sachin:123456@popo.cloudant.com
Waiting for CouchDB [--*---] SUCCESS
TypeError: Invalid Version: 72869b8
    at new SemVer (/Users/millisami/Hoodieaps/flourish/node_modules/hoodie-server/node_modules/semver/semver.js:295:11)
    at compare (/Users/millisami/Hoodieaps/flourish/node_modules/hoodie-server/node_modules/semver/semver.js:571:10)
    at Function.gte (/Users/millisami/Hoodieaps/flourish/node_modules/hoodie-server/node_modules/semver/semver.js:620:10)
    at exports.checkCouchVersion (/Users/millisami/Hoodieaps/flourish/node_modules/hoodie-server/lib/utils/couch.js:148:27)
    at /Users/millisami/Hoodieaps/flourish/node_modules/hoodie-server/node_modules/async/lib/async.js:1080:20
    at iterate (/Users/millisami/Hoodieaps/flourish/node_modules/hoodie-server/node_modules/async/lib/async.js:146:13)
    at /Users/millisami/Hoodieaps/flourish/node_modules/hoodie-server/node_modules/async/lib/async.js:157:25
    at Request._callback (/Users/millisami/Hoodieaps/flourish/node_modules/hoodie-server/lib/couchdb/index.js:135:16)
    at Request.self.callback (/Users/millisami/Hoodieaps/flourish/node_modules/hoodie-server/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
```

And in log it says:
```
Reading config from /Users/millisami/Hoodieaps/funcky/data/config.json.
```
which I don't have that file. I had before, but I deleted it.

**Comment by gr2m** [comment]
please see my comment here: https://github.com/hoodiehq/hoodie-server/issues/510#issuecomment-250578620
