### ISSUE TITLE
Too confusion setting up hoodie (TypeError: Invalid Version: 72869b8)

### ISSUE THREAD

**Issue by millisami** [hoodiehq/hoodie-server#513]
```
$ hoodie new testapp
$ cd testapp
$ hoodie start
```
And bam!! For me its not being that too easy, may be its in matuaring phase.

But its taking too long with iti (inception-to-inception) errors and now got one more inception to figure out.
i.e. After the db connection in successful, it blows up.
``` bash
.d$b.  .d$b.  .d$$$$$$b.    .d$$$$$$b.  .d$$$$$$b.  .d$b..d$$$$$$$$b.
$$$$$..$$$$$.$$$$$$$$$$$b .$$$$$$$$$$$b $$$$$$$$$$b $$$$$$$$$$$$$$$P'
$$$$$$$$$$$$d$$$$$$$$$$$$bd$$$$$$$$$$$$b$$$$$$$$$$$b$$$$$$$$$$$$$$$b.
$$$$$$$$$$$$Q$$$$$$$$$$$$PQ$$$$$$$$$$$$P$$$$$$$$$$$P$$$$$$$$$$$$$$$P'
$$$$$´`$$$$$'$$$$$$$$$$$$''$$$$$$$$$$$$'$$$$$$$$$$P $$$$$$$$$$$$$$$b.
'Q$P'  'Q$P'  'Q$$$$$$P'    'Q$$$$$$P'  'Q$$$$$$$P  'Q$P''Q$$$$$$$$P'

Version: 0.6.3 (node v2.3.0, npm 2.15.11, platform: darwin)

sys is deprecated. Use util instead.
Initializing...
Reading config from /Users/millisami/Hoodieaps/flourish/data/config.json.
Using remote CouchDB: https://abc:xyz@popo.cloudant.com
Waiting for CouchDB [--*---] SUCCESS
TypeError: Invalid Version: 72869b8
    at new SemVer (/Users/millisami/Hoodieaps/flourish/node_modules/hoodie-server/node_modules/semver/semver.js:295:11)
    at compare (/Users/millisami/Hoodieaps/flourish/node_modules/hoodie-server/node_modules/semver/semver.js:571:10)
    at Function.gte (/Users/millisami/Hoodieaps/flourish/node_modules/hoodie-server/node_modules/semver/semver.js:620:10)
    at exports.checkCouchVersion (/Users/millisami/Hoodieaps/flourish/node_modules/hoodie-server/lib/utils/couch.js:148:27)
    at /Users/millisami/Hoodieaps/flourish/node_modules/hoodie-server/node_modules/async/lib/async.js:1080:20
    at iterate (/Users/millisami/Hoodieaps/flourish/node_modules/hoodie-server/node_modules/async/lib/async.js:146:13)
    at /Users/millisami/Hoodieaps/flourish/node_modules/hoodie-server/node_modules/async/lib/async.js:157:25
    at Request._callback (/Users/millisami/Hoodieaps/flourish/node_modules/hoodie-server/lib/couchdb/index.js:135:16)
    at Request.self.callback (/Users/millisami/Hoodieaps/flourish/node_modules/hoodie-server/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
```

**Why semver is not working?**

My `package.json`

``` json
{
  "name": "flourish",
  "version": "3.2.1",
  "bundleDependencies": [
    "hoodie-plugin-appconfig",
    "hoodie-plugin-email",
    "hoodie-plugin-users",
    "hoodie-server"
  ],
  "dependencies": {
    "hoodie-plugin-appconfig": "^2.0.1",
    "hoodie-plugin-email": "^1.0.0",
    "hoodie-plugin-users": "^2.2.2",
    "hoodie-server": "^4.0.2"
  },
  "engines": {
    "node": ">=0.10.22"
  },
  "files": [
    "www/"
  ],
  "hoodie": {
    "plugins": [
      "hoodie-plugin-appconfig",
      "hoodie-plugin-email",
      "hoodie-plugin-users"
    ]
  },
  "scripts": {
    "start": "node node_modules/hoodie-server/bin/start"
  },
  "type": "app",
  "gitHead": "33fdb70357c415bbed56bbbd5197c805c0264294",
  "description": "[![Dependency Status](https://david-dm.org/hoodiehq/my-first-hoodie.svg)](https://david-dm.org/hoodiehq/my-first-hoodie)",
  "_id": "my-first-hoodie@3.2.1",
  "_shasum": "240df30b9664e56a04bb2ba2ad26c52e5691d763",
  "_from": "my-first-hoodie@3.2.1",
  "_npmVersion": "2.13.0",
  "_nodeVersion": "2.3.0",
  "_npmUser": {
    "name": "boennemann",
    "email": "stephan@boennemann.me"
  },
  "dist": {
    "shasum": "240df30b9664e56a04bb2ba2ad26c52e5691d763",
    "tarball": "https://registry.npmjs.org/my-first-hoodie/-/my-first-hoodie-3.2.1.tgz"
  },
  "maintainers": [
    {
      "name": "svnlto",
      "email": "me@svenlito.com"
    },
    {
      "name": "caolan",
      "email": "caolan.mcmahon@gmail.com"
    },
    {
      "name": "gr2m",
      "email": "gregor@martynus.net"
    },
    {
      "name": "jan",
      "email": "jan@apache.org"
    },
    {
      "name": "espy",
      "email": "hello@alexfeyerke.com"
    },
    {
      "name": "boennemann",
      "email": "stephan@boennemann.me"
    },
    {
      "name": "hoodiebot",
      "email": "stephan@thehoodiefirm.com"
    }
  ],
  "directories": {},
  "_resolved": "https://registry.npmjs.org/my-first-hoodie/-/my-first-hoodie-3.2.1.tgz",
  "readme": "ERROR: No README data found!"
}
```

**Comment by gr2m** [comment]
I’m very, very sorry for the frustration :( We are trying to resolve the confusion as fast as we can. Please follow my instructions at https://github.com/hoodiehq/hoodie-server/issues/510#issuecomment-250578620 to install the latest node and the latest Hoodie version
