### ISSUE TITLE
Waiting for CouchDB [---*--] FAILED 

### ISSUE THREAD

**Issue by haricodeharan** [hoodiehq/hoodie-server#546]
Error: Timed out waiting for CouchDB. These logs may help:
ERR! 	/home/server/namma_temple/hoodie_instruction/data/couch.stderr
ERR! 	/home/server/namma_temple/hoodie_instruction/data/couch.stdout
ERR! 	/home/server/namma_temple/hoodie_instruction/data/couch.log
ERR!     at Request._callback (/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/lib/couchdb/index.js:145:27)
ERR!     at self.callback (/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/request/request.js:197:22)
ERR!     at Request.emit (events.js:182:13)
ERR!     at Request.EventEmitter.emit (domain.js:442:20)
ERR!     at Request.onRequestError (/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/request/request.js:854:8)
ERR!     at ClientRequest.emit (events.js:182:13)
ERR!     at ClientRequest.EventEmitter.emit (domain.js:442:20)
ERR!     at Socket.socketErrorListener (_http_client.js:391:9)
ERR!     at Socket.emit (events.js:182:13)
ERR!     at Socket.EventEmitter.emit (domain.js:442:20)

**Comment by haricodeharan** [comment]
cat /home/server/.npm/_logs/2018-09-28T08_58_07_863Z-debug.log



0 info it worked if it ends with ok
1 verbose cli [ '/home/server/.nvm/versions/node/v10.11.0/bin/node',
1 verbose cli   '/home/server/.nvm/versions/node/v10.11.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle hoodie_instruction@3.2.1~prestart: hoodie_instruction@3.2.1
6 info lifecycle hoodie_instruction@3.2.1~start: hoodie_instruction@3.2.1
7 verbose lifecycle hoodie_instruction@3.2.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle hoodie_instruction@3.2.1~start: PATH: /home/server/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/server/namma_temple/hoodie_instruction/node_modules/.bin:/home/server/.nvm/versions/node/v10.11.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle hoodie_instruction@3.2.1~start: CWD: /home/server/namma_temple/hoodie_instruction
10 silly lifecycle hoodie_instruction@3.2.1~start: Args: [ '-c', 'node node_modules/hoodie-server/bin/start' ]
11 silly lifecycle hoodie_instruction@3.2.1~start: Returned: code: 1  signal: null
12 info lifecycle hoodie_instruction@3.2.1~start: Failed to exec start script
13 verbose stack Error: hoodie_instruction@3.2.1 start: `node node_modules/hoodie-server/bin/start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/server/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/server/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid hoodie_instruction@3.2.1
15 verbose cwd /home/server/namma_temple/hoodie_instruction
16 verbose Linux 4.15.0-34-generic
17 verbose argv "/home/server/.nvm/versions/node/v10.11.0/bin/node" "/home/server/.nvm/versions/node/v10.11.0/bin/npm" "start"
18 verbose node v10.11.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error hoodie_instruction@3.2.1 start: `node node_modules/hoodie-server/bin/start`
22 error Exit status 1
23 error Failed at the hoodie_instruction@3.2.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by haricodeharan** [comment]
IS the couchDB has problem??

cat /home/server/namma_temple/hoodie_instruction/data/couch.stderr


/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 1: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: mdfind: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 4: cd: can't cd to /Contents/Resources/couchdbx-core
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 5: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: ./bin/couchdb: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 1: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: mdfind: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 4: cd: can't cd to /Contents/Resources/couchdbx-core
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 5: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: ./bin/couchdb: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 1: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: mdfind: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 4: cd: can't cd to /Contents/Resources/couchdbx-core
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 5: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: ./bin/couchdb: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 1: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: mdfind: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 4: cd: can't cd to /Contents/Resources/couchdbx-core
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 5: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: ./bin/couchdb: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 1: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: mdfind: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 4: cd: can't cd to /Contents/Resources/couchdbx-core
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 5: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: ./bin/couchdb: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 1: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: mdfind: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 4: cd: can't cd to /Contents/Resources/couchdbx-core
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 5: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: ./bin/couchdb: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 1: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: mdfind: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 4: cd: can't cd to /Contents/Resources/couchdbx-core
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 5: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: ./bin/couchdb: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 1: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: mdfind: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 4: cd: can't cd to /Contents/Resources/couchdbx-core
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 5: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: ./bin/couchdb: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 1: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: mdfind: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 4: cd: can't cd to /Contents/Resources/couchdbx-core
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 5: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: ./bin/couchdb: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 1: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: mdfind: not found
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 4: cd: can't cd to /Contents/Resources/couchdbx-core
/home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: 5: /home/server/namma_temple/hoodie_instruction/node_modules/hoodie-server/node_modules/multicouch/bin/launch-couchdb-from-app.sh: ./bin/couchdb: not found
